log:
  stdout: true
  level: info

persistence:
  defaultStore: temporal
  visibilityStore: visibility
  numHistoryShards: 4
  datastores:
    temporal:
      sql:
        user: test
        password: password123
        pluginName: postgres12_pgx
        databaseName: temporal
        connectAddr: db:5432
        connectProtocol: tcp
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: 1h
        schemaName: public
    visibility:
      sql:
        user: test
        password: password123
        pluginName: postgres12_pgx
        databaseName: temporal_visibility
        connectAddr: db:5432
        connectProtocol: tcp
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: 1h
        schemaName: public

services:
  frontend:
    rpc:
      grpcPort: 7233
      membershipPort: 6933
      bindOnLocalHost: false
  matching:
    rpc:
      grpcPort: 7235
      membershipPort: 6935
      bindOnLocalHost: false
  history:
    rpc:
      grpcPort: 7234
      membershipPort: 6934
      bindOnLocalHost: false
  worker:
    rpc:
      grpcPort: 7236
      membershipPort: 6936
      bindOnLocalHost: false

global:
  pprof:
    port: 7936

kafka:
  tls:
    enabled: false

clusterMetadata:
  enableGlobalNamespace: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "frontend"
      rpcAddress: "127.0.0.1:7233"

dcRedirectionPolicy:
  policy: "noop"
  toDC: ""

archival:
  history:
    state: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
  visibility:
    state: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"

namespaceDefaults:
  archival:
    history:
      state: "enabled"
      URI: "file:///tmp/temporal_archival/development"
    visibility:
      state: "enabled"
      URI: "file:///tmp/temporal_archival/development"

k8s:
  serviceAccount:
    create: false
    name: temporal
