"""initial migration

Revision ID: 74bb29091b66
Revises: 
Create Date: 2025-06-27 21:10:58.698980+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '74bb29091b66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_source', sa.Enum('LINKEDIN', 'INDEED', name='jobsource'), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('job_url', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('new', sa.Boolean(), nullable=True),
    sa.Column('duplicate', sa.Boolean(), nullable=True),
    sa.Column('relevant', sa.Boolean(), nullable=True),
    sa.Column('promising', sa.Boolean(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('search_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_queries', sa.JSON(), nullable=False),
    sa.Column('desc_include_words', sa.JSON(), nullable=False),
    sa.Column('desc_exclude_words', sa.JSON(), nullable=False),
    sa.Column('title_include', sa.JSON(), nullable=False),
    sa.Column('title_exclude', sa.JSON(), nullable=False),
    sa.Column('company_exclude', sa.JSON(), nullable=False),
    sa.Column('non_remote_phrases', sa.JSON(), nullable=False),
    sa.Column('timespan', sa.String(length=100), nullable=False),
    sa.Column('pages_to_scrape', sa.Integer(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_settings_id'), 'search_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_settings_id'), table_name='search_settings')
    op.drop_table('search_settings')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
